const Menu = [
    {
        id:1,
        name: "Pizza",
        image: "images/image1.jpg",
        category: "Lunch",
        price:25,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:2,
        name: "Bread-Pakoda",
        image: "images/image2.jpg",
        category: "Lunch",
        price:30,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:3,
        name: "Chola",
        image: "images/image3.jpg",
        category: "Dinner",
        price:40,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:4,
        name: "Maggi",
        image: "images/image4.jpg",
        category: "BreakFast",
        price:15,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:5,
        name: "Non-Veg",
        image: "images/image5.webp",
        category: "Dinner",
        price:55,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:6,
        name: "Juice",
        image: "images/image6.jpg",
        category: "BreakFast",
        price:25,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:7,
        name: "Sandwich",
        image: "images/image7.jpg",
        category: "Lunch",
        price:33,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:8,
        name: "Ice-Cream",
        image: "images/image8.jpg",
        category: "Dinner",
        price:20,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:9,
        name: "Burger Combo",
        image: "images/image9.png",
        category: "Lunch",
        price:60,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
    {
        id:10,
        name: "Dahi-Bhlla",
        image: "images/image10.jpg",
        category: "BreakFast",
        price:28,
        description:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Rerumdicta fugiat repellat sit eius suscipit consectetur harum excepturiarchitecto consequuntur.",
    },
];

export default Menu;